services:
  game-server-demo:
    image: anla3421/game-server-demo:latest
    # image: game-server-demo:latest
    ports:
      - 5001:5001
      - 5000:5000
    networks:
      - rbac-network
  rbac-service:
    image: anla3421/rbac-service:latest
    # image: rbac-service:latest
    ports:
      - 5002:5002
    networks:
      - rbac-network
  db:
     image: mysql:8.4
     ports: 
       - 3306:3306
     environment:
        MYSQL_ROOT_PASSWORD: root
     volumes:
      - ./sqls:/docker-entrypoint-initdb.d
     networks:
      - rbac-network
  admin:
     image: adminer:5.2.1
     ports:
       - 8081:8080
     networks:
      - rbac-network

networks:
  rbac-network:
    driver: bridge